oauth_server_auth_login:
  pattern:  /oauth/v2/auth_login
  defaults: { _controller: NemizBundle:Security:login }
  
oauth_server_auth_login_check:
  pattern:  /oauth/v2/auth_login
  defaults: { _controller: NemizBundle:Security:loginCheck }

nemiz_default:
    resource: "@NemizBundle/Controller/DefaultController.php"
    type:     annotation

nemiz_api_profile:
    resource: "@NemizBundle/Controller/ProfileController.php"
    type:     annotation
    
nemiz_api_friends:
    resource: "@NemizBundle/Controller/FriendsController.php"
    type:     annotation
    
nemiz_api_devices:
    resource: "@NemizBundle/Controller/DeviceController.php"
    type:     annotation
    
nemiz_api_activity:
    resource: "@NemizBundle/Controller/ActivityController.php"
    type:     annotation                